services:
  db:
    image: postgres
    restart: always
    ports:
      - 5001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booksdb
volumes:
  pgdata:
